name: Windows MinGW Build

on: push

jobs:
  build-mingw:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x64]
        build_type: [Release, Debug]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # 安装 MinGW-w64 环境
      - name: Setup MinGW-w64
        uses: ilammy/setup-mingw@v1
        with:
          arch: ${{ matrix.arch }}

      # 缓存构建目录
      - name: Cache CMake build dir
        uses: actions/cache@v3
        with:
          path: build_mingw_${{ matrix.arch }}_${{ matrix.build_type }}
          key: ${{ runner.os }}-mingw-${{ matrix.arch }}-${{ matrix.build_type }}-${{ github.sha }}

      - name: CMake Configure & Build (MinGW Makefiles)
        run: |
          mkdir build_mingw_${{ matrix.arch }}_${{ matrix.build_type }}
          cd build_mingw_${{ matrix.arch }}_${{ matrix.build_type }}
          cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          mingw32-make -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-MinGW-${{ matrix.arch }}-${{ matrix.build_type }}-Bin
          path: |
            build_mingw_${{ matrix.arch }}_${{ matrix.build_type }}/**/*.exe
            build_mingw_${{ matrix.arch }}_${{ matrix.build_type }}/**/*.dll
          retention-days: 30